name: ci:test
on:
  - push
  - pull_request
jobs:
  test:
    name: Continuous integration (tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Install 🔧
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --ignore-scripts
          useRollingCache: true

      - name: Test 🔬
        run: yarn ci:test

      - name: Archive coverage data 💽
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: coverage
          include-hidden-files: true
          retention-days: 1

  test-coverage-upload:
    name: Continuous integration (tests coverage upload)

    needs:
      - test

    runs-on: ubuntu-latest

    timeout-minutes: 1

    steps:
      - name: Load coverage data 💽
        uses: actions/download-artifact@v8
        with:
          name: coverage
          path: coverage

      - name: Publish coverage report 📰
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: ./coverage/
          fail_ci_if_error: true
